export const QANDA_LIST_REQUEST = 'QANDA_LIST_REQUEST';
export const QANDA_LIST_SUCCESS = 'QANDA_LIST_SUCCESS';
export const QANDA_LIST_FAIL='QANDA_LIST_FAIL';

export const QANDA_CREATE_REQUEST = 'QANDA_CREATE_REQUEST';
export const QANDA_CREATE_SUCCESS = 'QANDA_CREATE_SUCCESS';
export const QANDA_CREATE_FAIL='QANDA_CREATE_FAIL';
export const QANDA_CREATE_RESET='QANDA_CREATE_RESET';

export const QANDA_DELETE_REQUEST = 'QANDA_DELETE_REQUEST';
export const QANDA_DELETE_SUCCESS = 'QANDA_DELETE_SUCCESS';
export const QANDA_DELETE_FAIL='QANDA_DELETE_FAIL';
export const QANDA_DELETE_RESET='QANDA_DELETE_RESET';

export const QANDA_UPDATE_REQUEST = 'QANDA_UPDATE_REQUEST';
export const QANDA_UPDATE_SUCCESS = 'QANDA_UPDATE_SUCCESS';
export const QANDA_UPDATE_FAIL = 'QANDA_UPDATE_FAIL';
export const QANDA_UPDATE_RESET = 'QANDA_UPDATE_RESET';

export const QANDA_DETAILS_REQUEST = 'QANDA_DETAILS_REQUEST';
export const QANDA_DETAILS_SUCCESS = 'QANDA_DETAILS_SUCCESS';
export const QANDA_DETAILS_FAIL = 'QANDA_DETAILS_FAIL';
