export const QANDA_LIST_REQUEST = 'QANDA_LIST_REQUEST';
export const QANDA_LIST_SUCCESS = 'QANDA_LIST_SUCCESS';
export const QANDA_LIST_FAIL='QANDA_LIST_FAIL';

export const QANDA_CREATE_REQUEST = 'QANDA_CREATE_REQUEST';
export const QANDA_CREATE_SUCCESS = 'QANDA_CREATE_SUCCESS';
export const QANDA_CREATE_FAIL='QANDA_CREATE_FAIL';
export const QANDA_CREATE_RESET='QANDA_CREATE_RESET';

export const QANDA_DELETE_REQUEST = 'QANDA_DELETE_REQUEST';
export const QANDA_DELETE_SUCCESS = 'QANDA_DELETE_SUCCESS';
export const QANDA_DELETE_FAIL='QANDA_DELETE_FAIL';
export const QANDA_DELETE_RESET='QANDA_DELETE_RESET';

export const QANDA_UPDATE_REQUEST = 'QANDA_UPDATE_REQUEST';
export const QANDA_UPDATE_SUCCESS = 'QANDA_UPDATE_SUCCESS';
export const QANDA_UPDATE_FAIL = 'QANDA_UPDATE_FAIL';
export const QANDA_UPDATE_RESET = 'QANDA_UPDATE_RESET';

export const QANDA_DETAILS_REQUEST = 'QANDA_DETAILS_REQUEST';
export const QANDA_DETAILS_SUCCESS = 'QANDA_DETAILS_SUCCESS';
export const QANDA_DETAILS_FAIL = 'QANDA_DETAILS_FAIL';

export const MESS_REPLY_QUESTION_REQUEST = 'MESS_REPLY_QUESTION_REQUEST';
export const MESS_REPLY_QUESTION_SUCCESS = 'MESS_REPLY_QUESTION_SUCCESS';
export const MESS_REPLY_QUESTION_FAIL = 'MESS_REPLY_QUESTION_FAIL';

export const TEXT_TO_SPEECH_SUCCESS = 'TEXT_TO_SPEECH_SUCCESS';
export const TEXT_TO_SPEECH_FAIL = 'TEXT_TO_SPEECH_FAIL';

export const CREATE_NEW_QUESTION_SUCCESS = 'CREATE_NEW_QUESTION_SUCCESS';
export const CREATE_NEW_QUESTION_FAIL = 'CREATE_NEW_QUESTION_FAIL';

export const LIST_NEW_QUESTION_REQUEST = 'LIST_NEW_QUESTION_REQUEST';
export const LIST_NEW_QUESTION_SUCCESS = 'LIST_NEW_QUESTION_SUCCESS';
export const LIST_NEW_QUESTION_FAIL = 'LIST_NEW_QUESTION_FAIL';

export const QUESTION_TRAIN_REQUEST = 'QUESTION_TRAIN_REQUEST';
export const QUESTION_TRAIN_SUCCESS = 'QUESTION_TRAIN_SUCCESS';
export const QUESTION_TRAIN_FAIL = 'QUESTION_TRAIN_FAIL';
export const QUESTION_TRAIN_RESET = 'QUESTION_TRAIN_RESET';

export const DATASET_LIST_REQUEST = 'DATASET_LIST_REQUEST';
export const DATASET_LIST_SUCCESS = 'DATASET_LIST_SUCCESS';
export const DATASET_LIST_FAIL = 'DATASET_LIST_FAIL';
export const DATASET_LIST_RESET = 'DATASET_LIST_RESET';

export const DATASET_DELETE_REQUEST = 'DATASET_DELETE_REQUEST';
export const DATASET_DELETE_SUCCESS = 'DATASET_DELETE_SUCCESS';
export const DATASET_DELETE_FAIL = 'DATASET_DELETE_FAIL';
export const DATASET_DELETE_RESET = 'DATASET_DELETE_RESET';

export const DATASET_DETAIL_REQUEST = 'DATASET_DETAIL_REQUEST';
export const DATASET_DETAIL_SUCCESS = 'DATASET_DETAIL_SUCCESS';
export const DATASET_DETAIL_FAIL = 'DATASET_DETAIL_FAIL';

export const DATASET_UPDATE_REQUEST = 'DATASET_UPDATE_REQUEST';
export const DATASET_UPDATE_SUCCESS = 'DATASET_UPDATE_SUCCESS';
export const DATASET_UPDATE_FAIL = 'DATASET_UPDATE_FAIL';
export const DATASET_UPDATE_RESET = 'DATASET_UPDATE_RESET';

//For check isAdmin Socket
export const ADMIN_ONLINE_SUCCESS = 'ADMIN_ONLINE_SUCCESS';
export const ADMIN_ONLINE_FAIL ='ADMIN_ONLINE_FAIL';
export const ADMIN_ONLINE_RESET = 'ADMIN_ONLINE_RESET';

